package main

type signal struct {
	group    group
	name     string
	locName  string
	content  string
	fineTune []fineTuneGroupID
}

var groupSignals = map[group][]signal{
	groupMath: {
		// expressions
		{name: "eq", locName: "Equal", content: "=", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnScaleMD,
		}},
		{name: "neq", locName: "Not Equal", content: "≠", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnScaleMD,
		}},
		{name: "aeq", locName: "Approximate Equal", content: "≈", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnScaleMD,
		}},
		{name: "gt", locName: "Greater Then", content: ">", fineTune: []fineTuneGroupID{
			fnScaleMD,
			ftOffsetRightXS,
		}},
		{name: "lt", locName: "Less Then", content: "<", fineTune: []fineTuneGroupID{
			fnScaleMD,
		}},
		{name: "ge", locName: "Greater or Equal", content: "≥", fineTune: []fineTuneGroupID{
			fnScaleMD,
		}},
		{name: "le", locName: "Less or Equal", content: "≤", fineTune: []fineTuneGroupID{
			fnScaleMD,
		}},
		{name: "plus", locName: "Plus", content: "+", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnScaleMD,
		}},
		{name: "minus", locName: "Minus", content: "-", fineTune: []fineTuneGroupID{
			ftOffsetUpLG,
			ftScaleXXL,
		}},
		{name: "plus_minus", locName: "Plus-Minus", content: "±", fineTune: []fineTuneGroupID{
			fnScaleMD,
		}},
		{name: "percent", locName: "Percent", content: "%", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
		}},
		{name: "percent_per_millie", locName: "Per-millie", content: "‰", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnUseLabelFont,
			fnScaleSM,
		}},
		{name: "one_percent", locName: "Percent", content: "1%", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
		}},
		// geo
		{name: "geo_angle", locName: "Angle", content: "∠", fineTune: []fineTuneGroupID{
			fnScaleMD,
		}},
		{name: "geo_perpendicular", locName: "Perpendicular", content: "⊥", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
		}},
		{name: "geo_parallel", locName: "Parallel", content: "∥", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
		}},
		{name: "geo_similar", locName: "Similar", content: "~", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnScaleMD,
		}},
		// algo
		{name: "algo_lemni", locName: "INF", content: "∞", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnScaleMD,
		}},
		{name: "algo_func", locName: "Function", content: "f", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnScaleMD,
		}},
		{name: "algo_delta", locName: "Delta", content: "∆", fineTune: []fineTuneGroupID{
			ftOffsetDownXS,
			fnScaleMD,
		}},
		{name: "algo_sigma", locName: "Sigma", content: "∑"},
		{name: "algo_golden", locName: "Golden", content: "φ"},
		{name: "algo_pi", locName: "PI", content: "π"},
		{name: "algo_integral", locName: "Integral", content: "∫"},
	},
	groupGreek: {
		{name: "alpha", locName: "Alpha", content: "α"},
		{name: "beta", locName: "Beta", content: "β"},
		{name: "gamma", locName: "Gamma", content: "γ"},
		{name: "delta", locName: "Delta", content: "δ"},
		{name: "epsilon", locName: "Epsilon", content: "ε"},
		{name: "zeta", locName: "Zeta", content: "ζ"},
		{name: "eta", locName: "Eta", content: "η"},
		{name: "theta", locName: "Theta", content: "θ"},
		{name: "iota", locName: "Iota", content: "ι"},
		{name: "kappa", locName: "Kappa", content: "κ"},
		{name: "lambda", locName: "Lambda", content: "λ"},
		{name: "mu", locName: "Mu", content: "μ"},
		{name: "nu", locName: "Nu", content: "ν"},
		{name: "xi", locName: "Xi", content: "ξ"},
		{name: "omicron", locName: "Omicron", content: "ο"},
		{name: "pi", locName: "Pi", content: "π"},
		{name: "rho", locName: "Rho", content: "ρ"},
		{name: "sigma", locName: "Sigma", content: "σ"},
		{name: "tau", locName: "Tau", content: "τ"},
		{name: "upsilon", locName: "Upsilon", content: "υ"},
		{name: "phi", locName: "Phi", content: "φ"},
		{name: "chi", locName: "Chi", content: "χ"},
		{name: "psi", locName: "Psi", content: "ψ"},
		{name: "omega", locName: "Omega", content: "ω"},
	},
	groupCommon: {
		{name: "on", locName: "ON", content: "ON"},
		{name: "off", locName: "OFF", content: "OFF"},
		{name: "min", locName: "MIN", content: "MIN"},
		{name: "max", locName: "MAX", content: "MAX"},
		{name: "in", locName: "IN", content: "IN"},
		{name: "out", locName: "OUT", content: "OUT"},
	},
	groupCommon2: {
		{name: "size", locName: "Size", content: "SIZE"},
		{name: "buffer", locName: "Buffer", content: "BUF"},
		{name: "cur", locName: "Current", content: "CUR"},
		{name: "limit", locName: "Limit", content: "LIM"},
		{name: "capacity", locName: "Capacity", content: "CAP"},
		{name: "nil", locName: "Nil", content: "NIL"},
		{name: "fuck", locName: "Fuck", content: "FUCK", fineTune: []fineTuneGroupID{fnUnScaleSM}},
		{name: "new", locName: "New", content: "NEW", fineTune: []fineTuneGroupID{fnUnScaleSM}},
		{name: "old", locName: "Old", content: "OLD"},
		{name: "ok", locName: "OK", content: "\uF00C", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "check", locName: "Check", content: "\uF560", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "stop", locName: "Stop", content: "\uF28D", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "low", locName: "Low", content: "LOW", fineTune: []fineTuneGroupID{fnUnScaleSM}},
		{name: "high", locName: "High", content: "HIGH", fineTune: []fineTuneGroupID{fnUnScaleSM}},
		{name: "full", locName: "Full", content: "FULL", fineTune: []fineTuneGroupID{fnUnScaleSM}},
	},
	groupCommon3: {
		{name: "size_small", locName: "Small", content: "SM"},
		{name: "size_medium", locName: "Medium", content: "MD"},
		{name: "size_large", locName: "Large", content: "LG"},
		{name: "size_extra_large", locName: "Extra Large", content: "XL"},
		{name: "size_xxl", locName: "XXL", content: "XXL"},
		{name: "sev_info", locName: "Info", content: "INF"},
		{name: "sev_warn", locName: "Warning", content: "WRN", fineTune: []fineTuneGroupID{fnUnScaleSM}},
		{name: "sev_err", locName: "Error", content: "ERR"},
		{name: "sev_critical", locName: "Critical", content: "CRT"},
		{name: "alert", locName: "Alert", content: "ALRT", fineTune: []fineTuneGroupID{fnUnScaleSM}},
		{name: "trigger", locName: "Trigger", content: "TRIG", fineTune: []fineTuneGroupID{fnUnScaleSM}},
		{name: "if", locName: "IF", content: "IF"},
		{name: "else", locName: "ELSE", content: "ELSE", fineTune: []fineTuneGroupID{fnUnScaleSM}},
		{name: "action", locName: "ACT", content: "ACT"},
		{name: "var_x", locName: "X", content: "X", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "var_y", locName: "Y", content: "Y", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "var_z", locName: "Z", content: "Z", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "var_w", locName: "W", content: "W", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "color_r", locName: "R", content: "R", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "color_g", locName: "G", content: "G", fineTune: []fineTuneGroupID{fnUseIconFont}},
		{name: "color_b", locName: "B", content: "B", fineTune: []fineTuneGroupID{fnUseIconFont}},
	},
	groupCommon4: {
		{name: "led1", locName: "L1", content: "L1"},
		{name: "led2", locName: "L2", content: "L2"},
		{name: "led3", locName: "L3", content: "L3"},
		{name: "led4", locName: "L4", content: "L4"},
		{name: "led5", locName: "L5", content: "L5"},
		{name: "led6", locName: "L6", content: "L6"},
		{name: "led7", locName: "L7", content: "L7"},
		{name: "led8", locName: "L8", content: "L8"},
		{name: "led9", locName: "L9", content: "L9"},
		{name: "reg0", locName: "R0", content: "R0"},
		{name: "reg1", locName: "R1", content: "R1"},
		{name: "reg2", locName: "R2", content: "R2"},
		{name: "reg3", locName: "R3", content: "R3"},
		{name: "reg4", locName: "R4", content: "R4"},
		{name: "reg5", locName: "R5", content: "R5"},
		{name: "reg6", locName: "R6", content: "R6"},
		{name: "reg7", locName: "R7", content: "R7"},
		{name: "reg8", locName: "R8", content: "R8"},
		{name: "reg9", locName: "R9", content: "R9"},
		{name: "reg0", locName: "R0", content: "R0"},
	},
	groupIcons: {
		{name: "stack", locName: "Stack", content: "\uF5FD"},
		{name: "load", locName: "Load", content: "\uF019"},
		{name: "unload", locName: "Unload", content: "\uF093"},
		{name: "train", locName: "Train", content: "\uF239"},
		{name: "ship", locName: "Ship", content: "\uF21A"},
		{name: "rocket", locName: "Rocket", content: "\uF135"},
		{name: "bell_on", locName: "Bell On", content: "\uF0F3"},
		{name: "bell_off", locName: "Bell Off", content: "\uF1F6"},
		{name: "question", locName: "Question", content: "?"},
		{name: "exclamation", locName: "Exclamation", content: "!"},
		{name: "plug", locName: "Plug", content: "\uF1E6"},
		{name: "puzzle", locName: "Puzzle", content: "\uF12E"},
		{name: "left", locName: "Left", content: "\uF30A"},
		{name: "right", locName: "Right", content: "\uF30B"},
		{name: "up", locName: "Up", content: "\uF30C"},
		{name: "down", locName: "Down", content: "\uF309"},
		{name: "location", locName: "Location", content: "\uF3C5"},
		{name: "power_exc", locName: "Power Warning", content: "\uE55D"},
		{name: "power_ok", locName: "Power OK", content: "\uE55C"},
		{name: "power_bolt", locName: "Power Bolt", content: "\uE55B"},
		{name: "wireless", locName: "Wireless", content: "\uF1EB"},
		{name: "signal", locName: "Some Signal", content: "\uF012"},
		{name: "broadcast", locName: "Broadcast", content: "\uF519"},
		{name: "satellite", locName: "Satellite", content: "\uF7C0"},
		{name: "satellite2", locName: "Satellite 2", content: "\uF7BF"},
		{name: "micro", locName: "Microchip", content: "\uF2DB"},
		{name: "env_bolt", locName: "Bolt", content: "\uF0E7"},
		{name: "env_fire", locName: "Fire", content: "\uF06D"},
		{name: "env_cold", locName: "Cold", content: "\uF2DC"},
		{name: "env_sun", locName: "Sun", content: "\uF185"},
		{name: "env_water", locName: "Water", content: "\uF773"},
		{name: "env_leaf", locName: "Leaf", content: "\uF06C"},
		{name: "env_wind", locName: "Wind", content: "\uF72E"},
		{name: "env_explosion", locName: "Explosion", content: "\uE4E9"},
		{name: "env_atom", locName: "Atom", content: "\uF5D2"},
		{name: "env_solar", locName: "Solar", content: "\uF5BA"},
		{name: "env_tree", locName: "Tree", content: "\uF1BB"},
		{name: "science", locName: "Science", content: "\uF0C3"},
		{name: "biters", locName: "Biters", content: "\uE4D0"},
		{name: "wrigglers", locName: "Wrigglers", content: "\uF717"},
	},
}
